// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy7JYyn0y9i19fNIAnP90TOa-xHa_U91o',
    appId: '1:732029231463:web:964dabd0f63ec90b2f8fc2',
    messagingSenderId: '732029231463',
    projectId: 'kampus-care',
    authDomain: 'kampus-care.firebaseapp.com',
    storageBucket: 'kampus-care.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Xh8VtmXoqI118Hd7kCv7gOencsjsZls',
    appId: '1:732029231463:android:b1eb72f2d1dea04e2f8fc2',
    messagingSenderId: '732029231463',
    projectId: 'kampus-care',
    storageBucket: 'kampus-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm7zZmqDCTx7PfOv3PFkwpwybkutwBP2s',
    appId: '1:732029231463:ios:3fabd0adf9ed95802f8fc2',
    messagingSenderId: '732029231463',
    projectId: 'kampus-care',
    storageBucket: 'kampus-care.firebasestorage.app',
    iosBundleId: 'com.example.kampusCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm7zZmqDCTx7PfOv3PFkwpwybkutwBP2s',
    appId: '1:732029231463:ios:3fabd0adf9ed95802f8fc2',
    messagingSenderId: '732029231463',
    projectId: 'kampus-care',
    storageBucket: 'kampus-care.firebasestorage.app',
    iosBundleId: 'com.example.kampusCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy7JYyn0y9i19fNIAnP90TOa-xHa_U91o',
    appId: '1:732029231463:web:a048e446fa5ded932f8fc2',
    messagingSenderId: '732029231463',
    projectId: 'kampus-care',
    authDomain: 'kampus-care.firebaseapp.com',
    storageBucket: 'kampus-care.firebasestorage.app',
  );
}
